[package]
name = "arch-bundler"
version = "0.1.0"
edition = "2024"

[dependencies]
alpm-compress = "0.1.2"
alpm-mtree = "0.3.2"
alpm-package = "0.4.1"
alpm-types = "0.11.1"
tempfile = "3.25.0"
testresult = "0.4.1"
